import { MigrationInterface, QueryRunner } from "typeorm";

export class CommunityCore1788638500000 implements MigrationInterface {
    name = 'CommunityCore1788638500000'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" varchar PRIMARY KEY NOT NULL, "actorUserId" integer, "actorRoles" text, "impersonatedByUserId" integer, "action" text NOT NULL, "entityType" text NOT NULL, "entityId" text, "before" text, "after" text, "reason" text, "ip" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE INDEX "IDX_e36d23e1e7cf81ea77758bef79" ON "audit_logs" ("actorUserId") `);
        await queryRunner.query(`CREATE INDEX "IDX_cee5459245f652b75eb2759b4c" ON "audit_logs" ("action") `);
        await queryRunner.query(`CREATE INDEX "IDX_c69efb19bf127c97e6740ad530" ON "audit_logs" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_13c69424c440a0e765053feb4b" ON "audit_logs" ("entityType", "entityId") `);
        await queryRunner.query(`CREATE TABLE "chapters" ("id" varchar PRIMARY KEY NOT NULL, "name" text NOT NULL, "code" text NOT NULL, "description" text, "leadUserId" integer, "contactEmail" text, "isActive" boolean NOT NULL DEFAULT (1), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_763fd9caff55ea1f33aa146a4b8" UNIQUE ("name"), CONSTRAINT "UQ_2b96c60371887d5903c9d3d5624" UNIQUE ("code"))`);
        await queryRunner.query(`CREATE INDEX "IDX_763fd9caff55ea1f33aa146a4b" ON "chapters" ("name") `);
        await queryRunner.query(`CREATE TABLE "households" ("id" varchar PRIMARY KEY NOT NULL, "publicHouseholdId" text NOT NULL, "headMemberId" text, "addressLine1" text, "addressLine2" text, "city" text, "state" text, "postalCode" text, "country" text NOT NULL DEFAULT ('US'), "chapter_id" varchar, "anniversaryDate" date, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_9641757bcd62af342e2aa5f7e17" UNIQUE ("publicHouseholdId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9641757bcd62af342e2aa5f7e1" ON "households" ("publicHouseholdId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d3f07b1964f2d0915e43fc8a4a" ON "households" ("chapter_id") `);
        await queryRunner.query(`CREATE TABLE "members" ("id" varchar PRIMARY KEY NOT NULL, "user_id" integer NOT NULL, "publicMemberId" text, "firstName" text NOT NULL, "middleName" text, "lastName" text NOT NULL, "honorific" text, "gender" text NOT NULL, "dateOfBirth" date NOT NULL, "thikana" text NOT NULL, "gotra" text NOT NULL, "caste" text NOT NULL, "sasural" text, "nanihal" text, "languages" text, "familyHistory" text, "phone" text NOT NULL, "whatsappPhone" text, "isPhoneVerified" boolean NOT NULL DEFAULT (0), "household_id" varchar NOT NULL, "relationship" text NOT NULL DEFAULT ('head_of_house'), "chapter_id" varchar, "chapterIsOverridden" boolean NOT NULL DEFAULT (0), "weddingDate" date, "industry" text, "jobTitle" text, "skills" text, "education" text, "linkedinUrl" text, "facebookUrl" text, "socialLinksApproved" boolean NOT NULL DEFAULT (0), "membershipTier" text NOT NULL, "joinDate" date, "volunteerInterests" text, "status" text NOT NULL DEFAULT ('pending_email_verification'), "rejectionReason" text, "rejectedAt" datetime, "infoRequestMessage" text, "infoRequestedAt" datetime, "archivedAt" datetime, "archivedByUserId" integer, "passwordSetAt" datetime, "isEmailVerified" boolean NOT NULL DEFAULT (0), "emailVerifiedAt" datetime, "emailVerificationProvenance" text, "emailOverrideByUserId" integer, "emailOverrideReason" text, "emailOverrideAt" datetime, "isApproved" boolean NOT NULL DEFAULT (0), "approvedByUserId" integer, "approvedAt" datetime, "isPaymentMade" boolean NOT NULL DEFAULT (0), "paymentOverrideByUserId" integer, "paymentOverrideReason" text, "paymentOverrideAt" datetime, "paymentSettledAt" datetime, "isActive" boolean NOT NULL DEFAULT (0), "activatedAt" datetime, "offlineVerification" boolean NOT NULL DEFAULT (0), "reviewerNotes" text, "directoryOptIn" boolean NOT NULL DEFAULT (1), "fieldVisibility" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_28d4bf9df97a869738824d37790" UNIQUE ("publicMemberId"), CONSTRAINT "REL_da404b5fd9c390e25338996e2d" UNIQUE ("user_id"), CONSTRAINT "CHK_member_active_implies_gates" CHECK ("isActive" = 0 OR ("isEmailVerified" = 1 AND "isApproved" = 1 AND "status" NOT IN ('rejected','archived'))))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_da404b5fd9c390e25338996e2d" ON "members" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_28d4bf9df97a869738824d3779" ON "members" ("publicMemberId") `);
        await queryRunner.query(`CREATE INDEX "IDX_b53ac7b9c0e30b89db66fea08a" ON "members" ("dateOfBirth") `);
        await queryRunner.query(`CREATE INDEX "IDX_b31db76278d10000e1b5c2ef71" ON "members" ("thikana") `);
        await queryRunner.query(`CREATE INDEX "IDX_a60514a7fb6a3e939833ee56ce" ON "members" ("gotra") `);
        await queryRunner.query(`CREATE INDEX "IDX_55cae358d5ad783201580ce1b7" ON "members" ("caste") `);
        await queryRunner.query(`CREATE INDEX "IDX_415e47bfa95b7897c35bdca642" ON "members" ("household_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_8b3cf72559bdc03150f5938d68" ON "members" ("chapter_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_d75eefa29c161d6add2a30a10e" ON "members" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_85d6263be6a57c16ad8b6c5ea6" ON "members" ("isActive") `);
        await queryRunner.query(`CREATE TABLE "child_profiles" ("id" varchar PRIMARY KEY NOT NULL, "member_id" varchar NOT NULL, "household_id" varchar NOT NULL, "firstName" text NOT NULL, "middleName" text, "lastName" text NOT NULL, "gender" text, "dateOfBirth" date NOT NULL, "sequence" integer NOT NULL DEFAULT (1), "educationLevel" text, "achievements" text, "membershipTier" text NOT NULL DEFAULT ('youth'), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE INDEX "IDX_2ce4cfcf429f873d6be38b2012" ON "child_profiles" ("member_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_3d0a56a2517d023beb8b8c5cc6" ON "child_profiles" ("household_id") `);
        await queryRunner.query(`CREATE TABLE "consent_records" ("id" varchar PRIMARY KEY NOT NULL, "member_id" varchar NOT NULL, "document" text NOT NULL, "version" text NOT NULL, "ip" text, "acceptedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE INDEX "IDX_b4b7f3910329a19c3e2df732b3" ON "consent_records" ("member_id", "document") `);
        await queryRunner.query(`CREATE TABLE "life_events" ("id" varchar PRIMARY KEY NOT NULL, "member_id" varchar NOT NULL, "type" text NOT NULL, "eventDate" date NOT NULL, "notes" text, "recognisedAt" datetime, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE INDEX "IDX_3b6ec7f6bf110870c935a88ff5" ON "life_events" ("member_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_bcf7ab15382d6fff4155ba9050" ON "life_events" ("eventDate") `);
        await queryRunner.query(`CREATE TABLE "member_reference_contacts" ("id" varchar PRIMARY KEY NOT NULL, "member_id" varchar NOT NULL, "sequence" integer NOT NULL, "name" text NOT NULL, "phone" text NOT NULL, "isVerified" boolean NOT NULL DEFAULT (0), "verifiedByUserId" integer, "verifiedAt" datetime, "notes" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE INDEX "IDX_e2daba4314a2d1ff3cd6da13ef" ON "member_reference_contacts" ("member_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_2dd2f29badf782c631f3b0b1ce" ON "member_reference_contacts" ("member_id", "sequence") `);
        await queryRunner.query(`CREATE TABLE "member_status_history" ("id" varchar PRIMARY KEY NOT NULL, "member_id" varchar NOT NULL, "fromStatus" text, "toStatus" text NOT NULL, "actorUserId" integer, "reason" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE INDEX "IDX_c1481e4dcfc0d9c1a9d8234741" ON "member_status_history" ("member_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c516f66beb4f46fa401ff7e7c6" ON "member_status_history" ("createdAt") `);
        await queryRunner.query(`CREATE TABLE "membership_payments" ("id" varchar PRIMARY KEY NOT NULL, "member_id" varchar NOT NULL, "tier" text NOT NULL, "amountCents" integer NOT NULL DEFAULT (0), "currency" text NOT NULL DEFAULT ('USD'), "status" text NOT NULL DEFAULT ('pending'), "provider" text, "providerRef" text, "reason" text, "recordedByUserId" integer, "settledAt" datetime, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE INDEX "IDX_733b90f80254aaa30625e3fdbb" ON "membership_payments" ("member_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_6065083ac6933eb65b540c2235" ON "membership_payments" ("status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_fa87cd9ac56f430865352a2e4d" ON "membership_payments" ("providerRef") `);
        await queryRunner.query(`CREATE TABLE "portal_settings" ("id" varchar PRIMARY KEY NOT NULL, "key" text NOT NULL, "value" text NOT NULL, "valueType" text NOT NULL DEFAULT ('string'), "description" text, "updatedByUserId" integer, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_2fe2408774bdc57318a5caeb1ca" UNIQUE ("key"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2fe2408774bdc57318a5caeb1c" ON "portal_settings" ("key") `);
        await queryRunner.query(`CREATE TABLE "reference_list_values" ("id" varchar PRIMARY KEY NOT NULL, "list_id" varchar NOT NULL, "value" text NOT NULL, "label" text NOT NULL, "sortOrder" integer NOT NULL DEFAULT (0), "isActive" boolean NOT NULL DEFAULT (1), "metadata" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE INDEX "IDX_2066b35f7bee316a15edc2a8a3" ON "reference_list_values" ("list_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e8aac809cc9b1242412d320f9e" ON "reference_list_values" ("list_id", "value") `);
        await queryRunner.query(`CREATE TABLE "reference_lists" ("id" varchar PRIMARY KEY NOT NULL, "key" text NOT NULL, "label" text NOT NULL, "description" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_50320ca4b20bbc129f231b2ef11" UNIQUE ("key"))`);
        await queryRunner.query(`CREATE INDEX "IDX_50320ca4b20bbc129f231b2ef1" ON "reference_lists" ("key") `);
        await queryRunner.query(`CREATE TABLE "spouse_profiles" ("id" varchar PRIMARY KEY NOT NULL, "member_id" varchar NOT NULL, "household_id" varchar NOT NULL, "firstName" text NOT NULL, "middleName" text, "lastName" text NOT NULL, "caste" text, "gotra" text, "thikana" text, "nanihal" text, "familyHistory" text, "email" text, "phone" text, "dateOfBirth" date, "industry" text, "education" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_8fabf47ae4fd06094e3b104183" ON "spouse_profiles" ("member_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_7d33fbb0642c39a3cb31b24e44" ON "spouse_profiles" ("household_id") `);
        await queryRunner.query(`CREATE TABLE "state_chapter_map" ("id" varchar PRIMARY KEY NOT NULL, "stateCode" text NOT NULL, "chapter_id" varchar NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_b10070b2dd28c5964761f1d5a2" ON "state_chapter_map" ("stateCode") `);
        await queryRunner.query(`CREATE INDEX "IDX_269a31bb7d188b362fe46086e8" ON "state_chapter_map" ("chapter_id") `);
        await queryRunner.query(`DROP INDEX "IDX_9641757bcd62af342e2aa5f7e1"`);
        await queryRunner.query(`DROP INDEX "IDX_d3f07b1964f2d0915e43fc8a4a"`);
        await queryRunner.query(`CREATE TABLE "temporary_households" ("id" varchar PRIMARY KEY NOT NULL, "publicHouseholdId" text NOT NULL, "headMemberId" text, "addressLine1" text, "addressLine2" text, "city" text, "state" text, "postalCode" text, "country" text NOT NULL DEFAULT ('US'), "chapter_id" varchar, "anniversaryDate" date, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_9641757bcd62af342e2aa5f7e17" UNIQUE ("publicHouseholdId"), CONSTRAINT "FK_d3f07b1964f2d0915e43fc8a4a2" FOREIGN KEY ("chapter_id") REFERENCES "chapters" ("id") ON DELETE SET NULL ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_households"("id", "publicHouseholdId", "headMemberId", "addressLine1", "addressLine2", "city", "state", "postalCode", "country", "chapter_id", "anniversaryDate", "createdAt", "updatedAt") SELECT "id", "publicHouseholdId", "headMemberId", "addressLine1", "addressLine2", "city", "state", "postalCode", "country", "chapter_id", "anniversaryDate", "createdAt", "updatedAt" FROM "households"`);
        await queryRunner.query(`DROP TABLE "households"`);
        await queryRunner.query(`ALTER TABLE "temporary_households" RENAME TO "households"`);
        await queryRunner.query(`CREATE INDEX "IDX_9641757bcd62af342e2aa5f7e1" ON "households" ("publicHouseholdId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d3f07b1964f2d0915e43fc8a4a" ON "households" ("chapter_id") `);
        await queryRunner.query(`DROP INDEX "IDX_da404b5fd9c390e25338996e2d"`);
        await queryRunner.query(`DROP INDEX "IDX_28d4bf9df97a869738824d3779"`);
        await queryRunner.query(`DROP INDEX "IDX_b53ac7b9c0e30b89db66fea08a"`);
        await queryRunner.query(`DROP INDEX "IDX_b31db76278d10000e1b5c2ef71"`);
        await queryRunner.query(`DROP INDEX "IDX_a60514a7fb6a3e939833ee56ce"`);
        await queryRunner.query(`DROP INDEX "IDX_55cae358d5ad783201580ce1b7"`);
        await queryRunner.query(`DROP INDEX "IDX_415e47bfa95b7897c35bdca642"`);
        await queryRunner.query(`DROP INDEX "IDX_8b3cf72559bdc03150f5938d68"`);
        await queryRunner.query(`DROP INDEX "IDX_d75eefa29c161d6add2a30a10e"`);
        await queryRunner.query(`DROP INDEX "IDX_85d6263be6a57c16ad8b6c5ea6"`);
        await queryRunner.query(`CREATE TABLE "temporary_members" ("id" varchar PRIMARY KEY NOT NULL, "user_id" integer NOT NULL, "publicMemberId" text, "firstName" text NOT NULL, "middleName" text, "lastName" text NOT NULL, "honorific" text, "gender" text NOT NULL, "dateOfBirth" date NOT NULL, "thikana" text NOT NULL, "gotra" text NOT NULL, "caste" text NOT NULL, "sasural" text, "nanihal" text, "languages" text, "familyHistory" text, "phone" text NOT NULL, "whatsappPhone" text, "isPhoneVerified" boolean NOT NULL DEFAULT (0), "household_id" varchar NOT NULL, "relationship" text NOT NULL DEFAULT ('head_of_house'), "chapter_id" varchar, "chapterIsOverridden" boolean NOT NULL DEFAULT (0), "weddingDate" date, "industry" text, "jobTitle" text, "skills" text, "education" text, "linkedinUrl" text, "facebookUrl" text, "socialLinksApproved" boolean NOT NULL DEFAULT (0), "membershipTier" text NOT NULL, "joinDate" date, "volunteerInterests" text, "status" text NOT NULL DEFAULT ('pending_email_verification'), "rejectionReason" text, "rejectedAt" datetime, "infoRequestMessage" text, "infoRequestedAt" datetime, "archivedAt" datetime, "archivedByUserId" integer, "passwordSetAt" datetime, "isEmailVerified" boolean NOT NULL DEFAULT (0), "emailVerifiedAt" datetime, "emailVerificationProvenance" text, "emailOverrideByUserId" integer, "emailOverrideReason" text, "emailOverrideAt" datetime, "isApproved" boolean NOT NULL DEFAULT (0), "approvedByUserId" integer, "approvedAt" datetime, "isPaymentMade" boolean NOT NULL DEFAULT (0), "paymentOverrideByUserId" integer, "paymentOverrideReason" text, "paymentOverrideAt" datetime, "paymentSettledAt" datetime, "isActive" boolean NOT NULL DEFAULT (0), "activatedAt" datetime, "offlineVerification" boolean NOT NULL DEFAULT (0), "reviewerNotes" text, "directoryOptIn" boolean NOT NULL DEFAULT (1), "fieldVisibility" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_28d4bf9df97a869738824d37790" UNIQUE ("publicMemberId"), CONSTRAINT "REL_da404b5fd9c390e25338996e2d" UNIQUE ("user_id"), CONSTRAINT "CHK_member_active_implies_gates" CHECK ("isActive" = 0 OR ("isEmailVerified" = 1 AND "isApproved" = 1 AND "status" NOT IN ('rejected','archived'))), CONSTRAINT "FK_da404b5fd9c390e25338996e2d1" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_415e47bfa95b7897c35bdca6421" FOREIGN KEY ("household_id") REFERENCES "households" ("id") ON DELETE RESTRICT ON UPDATE NO ACTION, CONSTRAINT "FK_8b3cf72559bdc03150f5938d683" FOREIGN KEY ("chapter_id") REFERENCES "chapters" ("id") ON DELETE SET NULL ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_members"("id", "user_id", "publicMemberId", "firstName", "middleName", "lastName", "honorific", "gender", "dateOfBirth", "thikana", "gotra", "caste", "sasural", "nanihal", "languages", "familyHistory", "phone", "whatsappPhone", "isPhoneVerified", "household_id", "relationship", "chapter_id", "chapterIsOverridden", "weddingDate", "industry", "jobTitle", "skills", "education", "linkedinUrl", "facebookUrl", "socialLinksApproved", "membershipTier", "joinDate", "volunteerInterests", "status", "rejectionReason", "rejectedAt", "infoRequestMessage", "infoRequestedAt", "archivedAt", "archivedByUserId", "passwordSetAt", "isEmailVerified", "emailVerifiedAt", "emailVerificationProvenance", "emailOverrideByUserId", "emailOverrideReason", "emailOverrideAt", "isApproved", "approvedByUserId", "approvedAt", "isPaymentMade", "paymentOverrideByUserId", "paymentOverrideReason", "paymentOverrideAt", "paymentSettledAt", "isActive", "activatedAt", "offlineVerification", "reviewerNotes", "directoryOptIn", "fieldVisibility", "createdAt", "updatedAt") SELECT "id", "user_id", "publicMemberId", "firstName", "middleName", "lastName", "honorific", "gender", "dateOfBirth", "thikana", "gotra", "caste", "sasural", "nanihal", "languages", "familyHistory", "phone", "whatsappPhone", "isPhoneVerified", "household_id", "relationship", "chapter_id", "chapterIsOverridden", "weddingDate", "industry", "jobTitle", "skills", "education", "linkedinUrl", "facebookUrl", "socialLinksApproved", "membershipTier", "joinDate", "volunteerInterests", "status", "rejectionReason", "rejectedAt", "infoRequestMessage", "infoRequestedAt", "archivedAt", "archivedByUserId", "passwordSetAt", "isEmailVerified", "emailVerifiedAt", "emailVerificationProvenance", "emailOverrideByUserId", "emailOverrideReason", "emailOverrideAt", "isApproved", "approvedByUserId", "approvedAt", "isPaymentMade", "paymentOverrideByUserId", "paymentOverrideReason", "paymentOverrideAt", "paymentSettledAt", "isActive", "activatedAt", "offlineVerification", "reviewerNotes", "directoryOptIn", "fieldVisibility", "createdAt", "updatedAt" FROM "members"`);
        await queryRunner.query(`DROP TABLE "members"`);
        await queryRunner.query(`ALTER TABLE "temporary_members" RENAME TO "members"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_da404b5fd9c390e25338996e2d" ON "members" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_28d4bf9df97a869738824d3779" ON "members" ("publicMemberId") `);
        await queryRunner.query(`CREATE INDEX "IDX_b53ac7b9c0e30b89db66fea08a" ON "members" ("dateOfBirth") `);
        await queryRunner.query(`CREATE INDEX "IDX_b31db76278d10000e1b5c2ef71" ON "members" ("thikana") `);
        await queryRunner.query(`CREATE INDEX "IDX_a60514a7fb6a3e939833ee56ce" ON "members" ("gotra") `);
        await queryRunner.query(`CREATE INDEX "IDX_55cae358d5ad783201580ce1b7" ON "members" ("caste") `);
        await queryRunner.query(`CREATE INDEX "IDX_415e47bfa95b7897c35bdca642" ON "members" ("household_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_8b3cf72559bdc03150f5938d68" ON "members" ("chapter_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_d75eefa29c161d6add2a30a10e" ON "members" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_85d6263be6a57c16ad8b6c5ea6" ON "members" ("isActive") `);
        await queryRunner.query(`DROP INDEX "IDX_2ce4cfcf429f873d6be38b2012"`);
        await queryRunner.query(`DROP INDEX "IDX_3d0a56a2517d023beb8b8c5cc6"`);
        await queryRunner.query(`CREATE TABLE "temporary_child_profiles" ("id" varchar PRIMARY KEY NOT NULL, "member_id" varchar NOT NULL, "household_id" varchar NOT NULL, "firstName" text NOT NULL, "middleName" text, "lastName" text NOT NULL, "gender" text, "dateOfBirth" date NOT NULL, "sequence" integer NOT NULL DEFAULT (1), "educationLevel" text, "achievements" text, "membershipTier" text NOT NULL DEFAULT ('youth'), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "FK_2ce4cfcf429f873d6be38b20126" FOREIGN KEY ("member_id") REFERENCES "members" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_3d0a56a2517d023beb8b8c5cc6e" FOREIGN KEY ("household_id") REFERENCES "households" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_child_profiles"("id", "member_id", "household_id", "firstName", "middleName", "lastName", "gender", "dateOfBirth", "sequence", "educationLevel", "achievements", "membershipTier", "createdAt", "updatedAt") SELECT "id", "member_id", "household_id", "firstName", "middleName", "lastName", "gender", "dateOfBirth", "sequence", "educationLevel", "achievements", "membershipTier", "createdAt", "updatedAt" FROM "child_profiles"`);
        await queryRunner.query(`DROP TABLE "child_profiles"`);
        await queryRunner.query(`ALTER TABLE "temporary_child_profiles" RENAME TO "child_profiles"`);
        await queryRunner.query(`CREATE INDEX "IDX_2ce4cfcf429f873d6be38b2012" ON "child_profiles" ("member_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_3d0a56a2517d023beb8b8c5cc6" ON "child_profiles" ("household_id") `);
        await queryRunner.query(`DROP INDEX "IDX_b4b7f3910329a19c3e2df732b3"`);
        await queryRunner.query(`CREATE TABLE "temporary_consent_records" ("id" varchar PRIMARY KEY NOT NULL, "member_id" varchar NOT NULL, "document" text NOT NULL, "version" text NOT NULL, "ip" text, "acceptedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "FK_0cee5ee945e53de41fc4d75f1b2" FOREIGN KEY ("member_id") REFERENCES "members" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_consent_records"("id", "member_id", "document", "version", "ip", "acceptedAt") SELECT "id", "member_id", "document", "version", "ip", "acceptedAt" FROM "consent_records"`);
        await queryRunner.query(`DROP TABLE "consent_records"`);
        await queryRunner.query(`ALTER TABLE "temporary_consent_records" RENAME TO "consent_records"`);
        await queryRunner.query(`CREATE INDEX "IDX_b4b7f3910329a19c3e2df732b3" ON "consent_records" ("member_id", "document") `);
        await queryRunner.query(`DROP INDEX "IDX_3b6ec7f6bf110870c935a88ff5"`);
        await queryRunner.query(`DROP INDEX "IDX_bcf7ab15382d6fff4155ba9050"`);
        await queryRunner.query(`CREATE TABLE "temporary_life_events" ("id" varchar PRIMARY KEY NOT NULL, "member_id" varchar NOT NULL, "type" text NOT NULL, "eventDate" date NOT NULL, "notes" text, "recognisedAt" datetime, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "FK_3b6ec7f6bf110870c935a88ff55" FOREIGN KEY ("member_id") REFERENCES "members" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_life_events"("id", "member_id", "type", "eventDate", "notes", "recognisedAt", "createdAt", "updatedAt") SELECT "id", "member_id", "type", "eventDate", "notes", "recognisedAt", "createdAt", "updatedAt" FROM "life_events"`);
        await queryRunner.query(`DROP TABLE "life_events"`);
        await queryRunner.query(`ALTER TABLE "temporary_life_events" RENAME TO "life_events"`);
        await queryRunner.query(`CREATE INDEX "IDX_3b6ec7f6bf110870c935a88ff5" ON "life_events" ("member_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_bcf7ab15382d6fff4155ba9050" ON "life_events" ("eventDate") `);
        await queryRunner.query(`DROP INDEX "IDX_e2daba4314a2d1ff3cd6da13ef"`);
        await queryRunner.query(`DROP INDEX "IDX_2dd2f29badf782c631f3b0b1ce"`);
        await queryRunner.query(`CREATE TABLE "temporary_member_reference_contacts" ("id" varchar PRIMARY KEY NOT NULL, "member_id" varchar NOT NULL, "sequence" integer NOT NULL, "name" text NOT NULL, "phone" text NOT NULL, "isVerified" boolean NOT NULL DEFAULT (0), "verifiedByUserId" integer, "verifiedAt" datetime, "notes" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "FK_e2daba4314a2d1ff3cd6da13eff" FOREIGN KEY ("member_id") REFERENCES "members" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_member_reference_contacts"("id", "member_id", "sequence", "name", "phone", "isVerified", "verifiedByUserId", "verifiedAt", "notes", "createdAt", "updatedAt") SELECT "id", "member_id", "sequence", "name", "phone", "isVerified", "verifiedByUserId", "verifiedAt", "notes", "createdAt", "updatedAt" FROM "member_reference_contacts"`);
        await queryRunner.query(`DROP TABLE "member_reference_contacts"`);
        await queryRunner.query(`ALTER TABLE "temporary_member_reference_contacts" RENAME TO "member_reference_contacts"`);
        await queryRunner.query(`CREATE INDEX "IDX_e2daba4314a2d1ff3cd6da13ef" ON "member_reference_contacts" ("member_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_2dd2f29badf782c631f3b0b1ce" ON "member_reference_contacts" ("member_id", "sequence") `);
        await queryRunner.query(`DROP INDEX "IDX_c1481e4dcfc0d9c1a9d8234741"`);
        await queryRunner.query(`DROP INDEX "IDX_c516f66beb4f46fa401ff7e7c6"`);
        await queryRunner.query(`CREATE TABLE "temporary_member_status_history" ("id" varchar PRIMARY KEY NOT NULL, "member_id" varchar NOT NULL, "fromStatus" text, "toStatus" text NOT NULL, "actorUserId" integer, "reason" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "FK_c1481e4dcfc0d9c1a9d82347414" FOREIGN KEY ("member_id") REFERENCES "members" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_member_status_history"("id", "member_id", "fromStatus", "toStatus", "actorUserId", "reason", "createdAt") SELECT "id", "member_id", "fromStatus", "toStatus", "actorUserId", "reason", "createdAt" FROM "member_status_history"`);
        await queryRunner.query(`DROP TABLE "member_status_history"`);
        await queryRunner.query(`ALTER TABLE "temporary_member_status_history" RENAME TO "member_status_history"`);
        await queryRunner.query(`CREATE INDEX "IDX_c1481e4dcfc0d9c1a9d8234741" ON "member_status_history" ("member_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c516f66beb4f46fa401ff7e7c6" ON "member_status_history" ("createdAt") `);
        await queryRunner.query(`DROP INDEX "IDX_733b90f80254aaa30625e3fdbb"`);
        await queryRunner.query(`DROP INDEX "IDX_6065083ac6933eb65b540c2235"`);
        await queryRunner.query(`DROP INDEX "IDX_fa87cd9ac56f430865352a2e4d"`);
        await queryRunner.query(`CREATE TABLE "temporary_membership_payments" ("id" varchar PRIMARY KEY NOT NULL, "member_id" varchar NOT NULL, "tier" text NOT NULL, "amountCents" integer NOT NULL DEFAULT (0), "currency" text NOT NULL DEFAULT ('USD'), "status" text NOT NULL DEFAULT ('pending'), "provider" text, "providerRef" text, "reason" text, "recordedByUserId" integer, "settledAt" datetime, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "FK_733b90f80254aaa30625e3fdbbf" FOREIGN KEY ("member_id") REFERENCES "members" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_membership_payments"("id", "member_id", "tier", "amountCents", "currency", "status", "provider", "providerRef", "reason", "recordedByUserId", "settledAt", "createdAt", "updatedAt") SELECT "id", "member_id", "tier", "amountCents", "currency", "status", "provider", "providerRef", "reason", "recordedByUserId", "settledAt", "createdAt", "updatedAt" FROM "membership_payments"`);
        await queryRunner.query(`DROP TABLE "membership_payments"`);
        await queryRunner.query(`ALTER TABLE "temporary_membership_payments" RENAME TO "membership_payments"`);
        await queryRunner.query(`CREATE INDEX "IDX_733b90f80254aaa30625e3fdbb" ON "membership_payments" ("member_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_6065083ac6933eb65b540c2235" ON "membership_payments" ("status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_fa87cd9ac56f430865352a2e4d" ON "membership_payments" ("providerRef") `);
        await queryRunner.query(`DROP INDEX "IDX_2066b35f7bee316a15edc2a8a3"`);
        await queryRunner.query(`DROP INDEX "IDX_e8aac809cc9b1242412d320f9e"`);
        await queryRunner.query(`CREATE TABLE "temporary_reference_list_values" ("id" varchar PRIMARY KEY NOT NULL, "list_id" varchar NOT NULL, "value" text NOT NULL, "label" text NOT NULL, "sortOrder" integer NOT NULL DEFAULT (0), "isActive" boolean NOT NULL DEFAULT (1), "metadata" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "FK_2066b35f7bee316a15edc2a8a3b" FOREIGN KEY ("list_id") REFERENCES "reference_lists" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_reference_list_values"("id", "list_id", "value", "label", "sortOrder", "isActive", "metadata", "createdAt", "updatedAt") SELECT "id", "list_id", "value", "label", "sortOrder", "isActive", "metadata", "createdAt", "updatedAt" FROM "reference_list_values"`);
        await queryRunner.query(`DROP TABLE "reference_list_values"`);
        await queryRunner.query(`ALTER TABLE "temporary_reference_list_values" RENAME TO "reference_list_values"`);
        await queryRunner.query(`CREATE INDEX "IDX_2066b35f7bee316a15edc2a8a3" ON "reference_list_values" ("list_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e8aac809cc9b1242412d320f9e" ON "reference_list_values" ("list_id", "value") `);
        await queryRunner.query(`DROP INDEX "IDX_8fabf47ae4fd06094e3b104183"`);
        await queryRunner.query(`DROP INDEX "IDX_7d33fbb0642c39a3cb31b24e44"`);
        await queryRunner.query(`CREATE TABLE "temporary_spouse_profiles" ("id" varchar PRIMARY KEY NOT NULL, "member_id" varchar NOT NULL, "household_id" varchar NOT NULL, "firstName" text NOT NULL, "middleName" text, "lastName" text NOT NULL, "caste" text, "gotra" text, "thikana" text, "nanihal" text, "familyHistory" text, "email" text, "phone" text, "dateOfBirth" date, "industry" text, "education" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "FK_8fabf47ae4fd06094e3b104183e" FOREIGN KEY ("member_id") REFERENCES "members" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_7d33fbb0642c39a3cb31b24e449" FOREIGN KEY ("household_id") REFERENCES "households" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_spouse_profiles"("id", "member_id", "household_id", "firstName", "middleName", "lastName", "caste", "gotra", "thikana", "nanihal", "familyHistory", "email", "phone", "dateOfBirth", "industry", "education", "createdAt", "updatedAt") SELECT "id", "member_id", "household_id", "firstName", "middleName", "lastName", "caste", "gotra", "thikana", "nanihal", "familyHistory", "email", "phone", "dateOfBirth", "industry", "education", "createdAt", "updatedAt" FROM "spouse_profiles"`);
        await queryRunner.query(`DROP TABLE "spouse_profiles"`);
        await queryRunner.query(`ALTER TABLE "temporary_spouse_profiles" RENAME TO "spouse_profiles"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_8fabf47ae4fd06094e3b104183" ON "spouse_profiles" ("member_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_7d33fbb0642c39a3cb31b24e44" ON "spouse_profiles" ("household_id") `);
        await queryRunner.query(`DROP INDEX "IDX_b10070b2dd28c5964761f1d5a2"`);
        await queryRunner.query(`DROP INDEX "IDX_269a31bb7d188b362fe46086e8"`);
        await queryRunner.query(`CREATE TABLE "temporary_state_chapter_map" ("id" varchar PRIMARY KEY NOT NULL, "stateCode" text NOT NULL, "chapter_id" varchar NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "FK_269a31bb7d188b362fe46086e8e" FOREIGN KEY ("chapter_id") REFERENCES "chapters" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_state_chapter_map"("id", "stateCode", "chapter_id", "createdAt", "updatedAt") SELECT "id", "stateCode", "chapter_id", "createdAt", "updatedAt" FROM "state_chapter_map"`);
        await queryRunner.query(`DROP TABLE "state_chapter_map"`);
        await queryRunner.query(`ALTER TABLE "temporary_state_chapter_map" RENAME TO "state_chapter_map"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_b10070b2dd28c5964761f1d5a2" ON "state_chapter_map" ("stateCode") `);
        await queryRunner.query(`CREATE INDEX "IDX_269a31bb7d188b362fe46086e8" ON "state_chapter_map" ("chapter_id") `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "IDX_269a31bb7d188b362fe46086e8"`);
        await queryRunner.query(`DROP INDEX "IDX_b10070b2dd28c5964761f1d5a2"`);
        await queryRunner.query(`ALTER TABLE "state_chapter_map" RENAME TO "temporary_state_chapter_map"`);
        await queryRunner.query(`CREATE TABLE "state_chapter_map" ("id" varchar PRIMARY KEY NOT NULL, "stateCode" text NOT NULL, "chapter_id" varchar NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`INSERT INTO "state_chapter_map"("id", "stateCode", "chapter_id", "createdAt", "updatedAt") SELECT "id", "stateCode", "chapter_id", "createdAt", "updatedAt" FROM "temporary_state_chapter_map"`);
        await queryRunner.query(`DROP TABLE "temporary_state_chapter_map"`);
        await queryRunner.query(`CREATE INDEX "IDX_269a31bb7d188b362fe46086e8" ON "state_chapter_map" ("chapter_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_b10070b2dd28c5964761f1d5a2" ON "state_chapter_map" ("stateCode") `);
        await queryRunner.query(`DROP INDEX "IDX_7d33fbb0642c39a3cb31b24e44"`);
        await queryRunner.query(`DROP INDEX "IDX_8fabf47ae4fd06094e3b104183"`);
        await queryRunner.query(`ALTER TABLE "spouse_profiles" RENAME TO "temporary_spouse_profiles"`);
        await queryRunner.query(`CREATE TABLE "spouse_profiles" ("id" varchar PRIMARY KEY NOT NULL, "member_id" varchar NOT NULL, "household_id" varchar NOT NULL, "firstName" text NOT NULL, "middleName" text, "lastName" text NOT NULL, "caste" text, "gotra" text, "thikana" text, "nanihal" text, "familyHistory" text, "email" text, "phone" text, "dateOfBirth" date, "industry" text, "education" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`INSERT INTO "spouse_profiles"("id", "member_id", "household_id", "firstName", "middleName", "lastName", "caste", "gotra", "thikana", "nanihal", "familyHistory", "email", "phone", "dateOfBirth", "industry", "education", "createdAt", "updatedAt") SELECT "id", "member_id", "household_id", "firstName", "middleName", "lastName", "caste", "gotra", "thikana", "nanihal", "familyHistory", "email", "phone", "dateOfBirth", "industry", "education", "createdAt", "updatedAt" FROM "temporary_spouse_profiles"`);
        await queryRunner.query(`DROP TABLE "temporary_spouse_profiles"`);
        await queryRunner.query(`CREATE INDEX "IDX_7d33fbb0642c39a3cb31b24e44" ON "spouse_profiles" ("household_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_8fabf47ae4fd06094e3b104183" ON "spouse_profiles" ("member_id") `);
        await queryRunner.query(`DROP INDEX "IDX_e8aac809cc9b1242412d320f9e"`);
        await queryRunner.query(`DROP INDEX "IDX_2066b35f7bee316a15edc2a8a3"`);
        await queryRunner.query(`ALTER TABLE "reference_list_values" RENAME TO "temporary_reference_list_values"`);
        await queryRunner.query(`CREATE TABLE "reference_list_values" ("id" varchar PRIMARY KEY NOT NULL, "list_id" varchar NOT NULL, "value" text NOT NULL, "label" text NOT NULL, "sortOrder" integer NOT NULL DEFAULT (0), "isActive" boolean NOT NULL DEFAULT (1), "metadata" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`INSERT INTO "reference_list_values"("id", "list_id", "value", "label", "sortOrder", "isActive", "metadata", "createdAt", "updatedAt") SELECT "id", "list_id", "value", "label", "sortOrder", "isActive", "metadata", "createdAt", "updatedAt" FROM "temporary_reference_list_values"`);
        await queryRunner.query(`DROP TABLE "temporary_reference_list_values"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e8aac809cc9b1242412d320f9e" ON "reference_list_values" ("list_id", "value") `);
        await queryRunner.query(`CREATE INDEX "IDX_2066b35f7bee316a15edc2a8a3" ON "reference_list_values" ("list_id") `);
        await queryRunner.query(`DROP INDEX "IDX_fa87cd9ac56f430865352a2e4d"`);
        await queryRunner.query(`DROP INDEX "IDX_6065083ac6933eb65b540c2235"`);
        await queryRunner.query(`DROP INDEX "IDX_733b90f80254aaa30625e3fdbb"`);
        await queryRunner.query(`ALTER TABLE "membership_payments" RENAME TO "temporary_membership_payments"`);
        await queryRunner.query(`CREATE TABLE "membership_payments" ("id" varchar PRIMARY KEY NOT NULL, "member_id" varchar NOT NULL, "tier" text NOT NULL, "amountCents" integer NOT NULL DEFAULT (0), "currency" text NOT NULL DEFAULT ('USD'), "status" text NOT NULL DEFAULT ('pending'), "provider" text, "providerRef" text, "reason" text, "recordedByUserId" integer, "settledAt" datetime, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`INSERT INTO "membership_payments"("id", "member_id", "tier", "amountCents", "currency", "status", "provider", "providerRef", "reason", "recordedByUserId", "settledAt", "createdAt", "updatedAt") SELECT "id", "member_id", "tier", "amountCents", "currency", "status", "provider", "providerRef", "reason", "recordedByUserId", "settledAt", "createdAt", "updatedAt" FROM "temporary_membership_payments"`);
        await queryRunner.query(`DROP TABLE "temporary_membership_payments"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_fa87cd9ac56f430865352a2e4d" ON "membership_payments" ("providerRef") `);
        await queryRunner.query(`CREATE INDEX "IDX_6065083ac6933eb65b540c2235" ON "membership_payments" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_733b90f80254aaa30625e3fdbb" ON "membership_payments" ("member_id") `);
        await queryRunner.query(`DROP INDEX "IDX_c516f66beb4f46fa401ff7e7c6"`);
        await queryRunner.query(`DROP INDEX "IDX_c1481e4dcfc0d9c1a9d8234741"`);
        await queryRunner.query(`ALTER TABLE "member_status_history" RENAME TO "temporary_member_status_history"`);
        await queryRunner.query(`CREATE TABLE "member_status_history" ("id" varchar PRIMARY KEY NOT NULL, "member_id" varchar NOT NULL, "fromStatus" text, "toStatus" text NOT NULL, "actorUserId" integer, "reason" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`INSERT INTO "member_status_history"("id", "member_id", "fromStatus", "toStatus", "actorUserId", "reason", "createdAt") SELECT "id", "member_id", "fromStatus", "toStatus", "actorUserId", "reason", "createdAt" FROM "temporary_member_status_history"`);
        await queryRunner.query(`DROP TABLE "temporary_member_status_history"`);
        await queryRunner.query(`CREATE INDEX "IDX_c516f66beb4f46fa401ff7e7c6" ON "member_status_history" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_c1481e4dcfc0d9c1a9d8234741" ON "member_status_history" ("member_id") `);
        await queryRunner.query(`DROP INDEX "IDX_2dd2f29badf782c631f3b0b1ce"`);
        await queryRunner.query(`DROP INDEX "IDX_e2daba4314a2d1ff3cd6da13ef"`);
        await queryRunner.query(`ALTER TABLE "member_reference_contacts" RENAME TO "temporary_member_reference_contacts"`);
        await queryRunner.query(`CREATE TABLE "member_reference_contacts" ("id" varchar PRIMARY KEY NOT NULL, "member_id" varchar NOT NULL, "sequence" integer NOT NULL, "name" text NOT NULL, "phone" text NOT NULL, "isVerified" boolean NOT NULL DEFAULT (0), "verifiedByUserId" integer, "verifiedAt" datetime, "notes" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`INSERT INTO "member_reference_contacts"("id", "member_id", "sequence", "name", "phone", "isVerified", "verifiedByUserId", "verifiedAt", "notes", "createdAt", "updatedAt") SELECT "id", "member_id", "sequence", "name", "phone", "isVerified", "verifiedByUserId", "verifiedAt", "notes", "createdAt", "updatedAt" FROM "temporary_member_reference_contacts"`);
        await queryRunner.query(`DROP TABLE "temporary_member_reference_contacts"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_2dd2f29badf782c631f3b0b1ce" ON "member_reference_contacts" ("member_id", "sequence") `);
        await queryRunner.query(`CREATE INDEX "IDX_e2daba4314a2d1ff3cd6da13ef" ON "member_reference_contacts" ("member_id") `);
        await queryRunner.query(`DROP INDEX "IDX_bcf7ab15382d6fff4155ba9050"`);
        await queryRunner.query(`DROP INDEX "IDX_3b6ec7f6bf110870c935a88ff5"`);
        await queryRunner.query(`ALTER TABLE "life_events" RENAME TO "temporary_life_events"`);
        await queryRunner.query(`CREATE TABLE "life_events" ("id" varchar PRIMARY KEY NOT NULL, "member_id" varchar NOT NULL, "type" text NOT NULL, "eventDate" date NOT NULL, "notes" text, "recognisedAt" datetime, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`INSERT INTO "life_events"("id", "member_id", "type", "eventDate", "notes", "recognisedAt", "createdAt", "updatedAt") SELECT "id", "member_id", "type", "eventDate", "notes", "recognisedAt", "createdAt", "updatedAt" FROM "temporary_life_events"`);
        await queryRunner.query(`DROP TABLE "temporary_life_events"`);
        await queryRunner.query(`CREATE INDEX "IDX_bcf7ab15382d6fff4155ba9050" ON "life_events" ("eventDate") `);
        await queryRunner.query(`CREATE INDEX "IDX_3b6ec7f6bf110870c935a88ff5" ON "life_events" ("member_id") `);
        await queryRunner.query(`DROP INDEX "IDX_b4b7f3910329a19c3e2df732b3"`);
        await queryRunner.query(`ALTER TABLE "consent_records" RENAME TO "temporary_consent_records"`);
        await queryRunner.query(`CREATE TABLE "consent_records" ("id" varchar PRIMARY KEY NOT NULL, "member_id" varchar NOT NULL, "document" text NOT NULL, "version" text NOT NULL, "ip" text, "acceptedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`INSERT INTO "consent_records"("id", "member_id", "document", "version", "ip", "acceptedAt") SELECT "id", "member_id", "document", "version", "ip", "acceptedAt" FROM "temporary_consent_records"`);
        await queryRunner.query(`DROP TABLE "temporary_consent_records"`);
        await queryRunner.query(`CREATE INDEX "IDX_b4b7f3910329a19c3e2df732b3" ON "consent_records" ("member_id", "document") `);
        await queryRunner.query(`DROP INDEX "IDX_3d0a56a2517d023beb8b8c5cc6"`);
        await queryRunner.query(`DROP INDEX "IDX_2ce4cfcf429f873d6be38b2012"`);
        await queryRunner.query(`ALTER TABLE "child_profiles" RENAME TO "temporary_child_profiles"`);
        await queryRunner.query(`CREATE TABLE "child_profiles" ("id" varchar PRIMARY KEY NOT NULL, "member_id" varchar NOT NULL, "household_id" varchar NOT NULL, "firstName" text NOT NULL, "middleName" text, "lastName" text NOT NULL, "gender" text, "dateOfBirth" date NOT NULL, "sequence" integer NOT NULL DEFAULT (1), "educationLevel" text, "achievements" text, "membershipTier" text NOT NULL DEFAULT ('youth'), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`INSERT INTO "child_profiles"("id", "member_id", "household_id", "firstName", "middleName", "lastName", "gender", "dateOfBirth", "sequence", "educationLevel", "achievements", "membershipTier", "createdAt", "updatedAt") SELECT "id", "member_id", "household_id", "firstName", "middleName", "lastName", "gender", "dateOfBirth", "sequence", "educationLevel", "achievements", "membershipTier", "createdAt", "updatedAt" FROM "temporary_child_profiles"`);
        await queryRunner.query(`DROP TABLE "temporary_child_profiles"`);
        await queryRunner.query(`CREATE INDEX "IDX_3d0a56a2517d023beb8b8c5cc6" ON "child_profiles" ("household_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_2ce4cfcf429f873d6be38b2012" ON "child_profiles" ("member_id") `);
        await queryRunner.query(`DROP INDEX "IDX_85d6263be6a57c16ad8b6c5ea6"`);
        await queryRunner.query(`DROP INDEX "IDX_d75eefa29c161d6add2a30a10e"`);
        await queryRunner.query(`DROP INDEX "IDX_8b3cf72559bdc03150f5938d68"`);
        await queryRunner.query(`DROP INDEX "IDX_415e47bfa95b7897c35bdca642"`);
        await queryRunner.query(`DROP INDEX "IDX_55cae358d5ad783201580ce1b7"`);
        await queryRunner.query(`DROP INDEX "IDX_a60514a7fb6a3e939833ee56ce"`);
        await queryRunner.query(`DROP INDEX "IDX_b31db76278d10000e1b5c2ef71"`);
        await queryRunner.query(`DROP INDEX "IDX_b53ac7b9c0e30b89db66fea08a"`);
        await queryRunner.query(`DROP INDEX "IDX_28d4bf9df97a869738824d3779"`);
        await queryRunner.query(`DROP INDEX "IDX_da404b5fd9c390e25338996e2d"`);
        await queryRunner.query(`ALTER TABLE "members" RENAME TO "temporary_members"`);
        await queryRunner.query(`CREATE TABLE "members" ("id" varchar PRIMARY KEY NOT NULL, "user_id" integer NOT NULL, "publicMemberId" text, "firstName" text NOT NULL, "middleName" text, "lastName" text NOT NULL, "honorific" text, "gender" text NOT NULL, "dateOfBirth" date NOT NULL, "thikana" text NOT NULL, "gotra" text NOT NULL, "caste" text NOT NULL, "sasural" text, "nanihal" text, "languages" text, "familyHistory" text, "phone" text NOT NULL, "whatsappPhone" text, "isPhoneVerified" boolean NOT NULL DEFAULT (0), "household_id" varchar NOT NULL, "relationship" text NOT NULL DEFAULT ('head_of_house'), "chapter_id" varchar, "chapterIsOverridden" boolean NOT NULL DEFAULT (0), "weddingDate" date, "industry" text, "jobTitle" text, "skills" text, "education" text, "linkedinUrl" text, "facebookUrl" text, "socialLinksApproved" boolean NOT NULL DEFAULT (0), "membershipTier" text NOT NULL, "joinDate" date, "volunteerInterests" text, "status" text NOT NULL DEFAULT ('pending_email_verification'), "rejectionReason" text, "rejectedAt" datetime, "infoRequestMessage" text, "infoRequestedAt" datetime, "archivedAt" datetime, "archivedByUserId" integer, "passwordSetAt" datetime, "isEmailVerified" boolean NOT NULL DEFAULT (0), "emailVerifiedAt" datetime, "emailVerificationProvenance" text, "emailOverrideByUserId" integer, "emailOverrideReason" text, "emailOverrideAt" datetime, "isApproved" boolean NOT NULL DEFAULT (0), "approvedByUserId" integer, "approvedAt" datetime, "isPaymentMade" boolean NOT NULL DEFAULT (0), "paymentOverrideByUserId" integer, "paymentOverrideReason" text, "paymentOverrideAt" datetime, "paymentSettledAt" datetime, "isActive" boolean NOT NULL DEFAULT (0), "activatedAt" datetime, "offlineVerification" boolean NOT NULL DEFAULT (0), "reviewerNotes" text, "directoryOptIn" boolean NOT NULL DEFAULT (1), "fieldVisibility" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_28d4bf9df97a869738824d37790" UNIQUE ("publicMemberId"), CONSTRAINT "REL_da404b5fd9c390e25338996e2d" UNIQUE ("user_id"), CONSTRAINT "CHK_member_active_implies_gates" CHECK ("isActive" = 0 OR ("isEmailVerified" = 1 AND "isApproved" = 1 AND "status" NOT IN ('rejected','archived'))))`);
        await queryRunner.query(`INSERT INTO "members"("id", "user_id", "publicMemberId", "firstName", "middleName", "lastName", "honorific", "gender", "dateOfBirth", "thikana", "gotra", "caste", "sasural", "nanihal", "languages", "familyHistory", "phone", "whatsappPhone", "isPhoneVerified", "household_id", "relationship", "chapter_id", "chapterIsOverridden", "weddingDate", "industry", "jobTitle", "skills", "education", "linkedinUrl", "facebookUrl", "socialLinksApproved", "membershipTier", "joinDate", "volunteerInterests", "status", "rejectionReason", "rejectedAt", "infoRequestMessage", "infoRequestedAt", "archivedAt", "archivedByUserId", "passwordSetAt", "isEmailVerified", "emailVerifiedAt", "emailVerificationProvenance", "emailOverrideByUserId", "emailOverrideReason", "emailOverrideAt", "isApproved", "approvedByUserId", "approvedAt", "isPaymentMade", "paymentOverrideByUserId", "paymentOverrideReason", "paymentOverrideAt", "paymentSettledAt", "isActive", "activatedAt", "offlineVerification", "reviewerNotes", "directoryOptIn", "fieldVisibility", "createdAt", "updatedAt") SELECT "id", "user_id", "publicMemberId", "firstName", "middleName", "lastName", "honorific", "gender", "dateOfBirth", "thikana", "gotra", "caste", "sasural", "nanihal", "languages", "familyHistory", "phone", "whatsappPhone", "isPhoneVerified", "household_id", "relationship", "chapter_id", "chapterIsOverridden", "weddingDate", "industry", "jobTitle", "skills", "education", "linkedinUrl", "facebookUrl", "socialLinksApproved", "membershipTier", "joinDate", "volunteerInterests", "status", "rejectionReason", "rejectedAt", "infoRequestMessage", "infoRequestedAt", "archivedAt", "archivedByUserId", "passwordSetAt", "isEmailVerified", "emailVerifiedAt", "emailVerificationProvenance", "emailOverrideByUserId", "emailOverrideReason", "emailOverrideAt", "isApproved", "approvedByUserId", "approvedAt", "isPaymentMade", "paymentOverrideByUserId", "paymentOverrideReason", "paymentOverrideAt", "paymentSettledAt", "isActive", "activatedAt", "offlineVerification", "reviewerNotes", "directoryOptIn", "fieldVisibility", "createdAt", "updatedAt" FROM "temporary_members"`);
        await queryRunner.query(`DROP TABLE "temporary_members"`);
        await queryRunner.query(`CREATE INDEX "IDX_85d6263be6a57c16ad8b6c5ea6" ON "members" ("isActive") `);
        await queryRunner.query(`CREATE INDEX "IDX_d75eefa29c161d6add2a30a10e" ON "members" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_8b3cf72559bdc03150f5938d68" ON "members" ("chapter_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_415e47bfa95b7897c35bdca642" ON "members" ("household_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_55cae358d5ad783201580ce1b7" ON "members" ("caste") `);
        await queryRunner.query(`CREATE INDEX "IDX_a60514a7fb6a3e939833ee56ce" ON "members" ("gotra") `);
        await queryRunner.query(`CREATE INDEX "IDX_b31db76278d10000e1b5c2ef71" ON "members" ("thikana") `);
        await queryRunner.query(`CREATE INDEX "IDX_b53ac7b9c0e30b89db66fea08a" ON "members" ("dateOfBirth") `);
        await queryRunner.query(`CREATE INDEX "IDX_28d4bf9df97a869738824d3779" ON "members" ("publicMemberId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_da404b5fd9c390e25338996e2d" ON "members" ("user_id") `);
        await queryRunner.query(`DROP INDEX "IDX_d3f07b1964f2d0915e43fc8a4a"`);
        await queryRunner.query(`DROP INDEX "IDX_9641757bcd62af342e2aa5f7e1"`);
        await queryRunner.query(`ALTER TABLE "households" RENAME TO "temporary_households"`);
        await queryRunner.query(`CREATE TABLE "households" ("id" varchar PRIMARY KEY NOT NULL, "publicHouseholdId" text NOT NULL, "headMemberId" text, "addressLine1" text, "addressLine2" text, "city" text, "state" text, "postalCode" text, "country" text NOT NULL DEFAULT ('US'), "chapter_id" varchar, "anniversaryDate" date, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_9641757bcd62af342e2aa5f7e17" UNIQUE ("publicHouseholdId"))`);
        await queryRunner.query(`INSERT INTO "households"("id", "publicHouseholdId", "headMemberId", "addressLine1", "addressLine2", "city", "state", "postalCode", "country", "chapter_id", "anniversaryDate", "createdAt", "updatedAt") SELECT "id", "publicHouseholdId", "headMemberId", "addressLine1", "addressLine2", "city", "state", "postalCode", "country", "chapter_id", "anniversaryDate", "createdAt", "updatedAt" FROM "temporary_households"`);
        await queryRunner.query(`DROP TABLE "temporary_households"`);
        await queryRunner.query(`CREATE INDEX "IDX_d3f07b1964f2d0915e43fc8a4a" ON "households" ("chapter_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_9641757bcd62af342e2aa5f7e1" ON "households" ("publicHouseholdId") `);
        await queryRunner.query(`DROP INDEX "IDX_269a31bb7d188b362fe46086e8"`);
        await queryRunner.query(`DROP INDEX "IDX_b10070b2dd28c5964761f1d5a2"`);
        await queryRunner.query(`DROP TABLE "state_chapter_map"`);
        await queryRunner.query(`DROP INDEX "IDX_7d33fbb0642c39a3cb31b24e44"`);
        await queryRunner.query(`DROP INDEX "IDX_8fabf47ae4fd06094e3b104183"`);
        await queryRunner.query(`DROP TABLE "spouse_profiles"`);
        await queryRunner.query(`DROP INDEX "IDX_50320ca4b20bbc129f231b2ef1"`);
        await queryRunner.query(`DROP TABLE "reference_lists"`);
        await queryRunner.query(`DROP INDEX "IDX_e8aac809cc9b1242412d320f9e"`);
        await queryRunner.query(`DROP INDEX "IDX_2066b35f7bee316a15edc2a8a3"`);
        await queryRunner.query(`DROP TABLE "reference_list_values"`);
        await queryRunner.query(`DROP INDEX "IDX_2fe2408774bdc57318a5caeb1c"`);
        await queryRunner.query(`DROP TABLE "portal_settings"`);
        await queryRunner.query(`DROP INDEX "IDX_fa87cd9ac56f430865352a2e4d"`);
        await queryRunner.query(`DROP INDEX "IDX_6065083ac6933eb65b540c2235"`);
        await queryRunner.query(`DROP INDEX "IDX_733b90f80254aaa30625e3fdbb"`);
        await queryRunner.query(`DROP TABLE "membership_payments"`);
        await queryRunner.query(`DROP INDEX "IDX_c516f66beb4f46fa401ff7e7c6"`);
        await queryRunner.query(`DROP INDEX "IDX_c1481e4dcfc0d9c1a9d8234741"`);
        await queryRunner.query(`DROP TABLE "member_status_history"`);
        await queryRunner.query(`DROP INDEX "IDX_2dd2f29badf782c631f3b0b1ce"`);
        await queryRunner.query(`DROP INDEX "IDX_e2daba4314a2d1ff3cd6da13ef"`);
        await queryRunner.query(`DROP TABLE "member_reference_contacts"`);
        await queryRunner.query(`DROP INDEX "IDX_bcf7ab15382d6fff4155ba9050"`);
        await queryRunner.query(`DROP INDEX "IDX_3b6ec7f6bf110870c935a88ff5"`);
        await queryRunner.query(`DROP TABLE "life_events"`);
        await queryRunner.query(`DROP INDEX "IDX_b4b7f3910329a19c3e2df732b3"`);
        await queryRunner.query(`DROP TABLE "consent_records"`);
        await queryRunner.query(`DROP INDEX "IDX_3d0a56a2517d023beb8b8c5cc6"`);
        await queryRunner.query(`DROP INDEX "IDX_2ce4cfcf429f873d6be38b2012"`);
        await queryRunner.query(`DROP TABLE "child_profiles"`);
        await queryRunner.query(`DROP INDEX "IDX_85d6263be6a57c16ad8b6c5ea6"`);
        await queryRunner.query(`DROP INDEX "IDX_d75eefa29c161d6add2a30a10e"`);
        await queryRunner.query(`DROP INDEX "IDX_8b3cf72559bdc03150f5938d68"`);
        await queryRunner.query(`DROP INDEX "IDX_415e47bfa95b7897c35bdca642"`);
        await queryRunner.query(`DROP INDEX "IDX_55cae358d5ad783201580ce1b7"`);
        await queryRunner.query(`DROP INDEX "IDX_a60514a7fb6a3e939833ee56ce"`);
        await queryRunner.query(`DROP INDEX "IDX_b31db76278d10000e1b5c2ef71"`);
        await queryRunner.query(`DROP INDEX "IDX_b53ac7b9c0e30b89db66fea08a"`);
        await queryRunner.query(`DROP INDEX "IDX_28d4bf9df97a869738824d3779"`);
        await queryRunner.query(`DROP INDEX "IDX_da404b5fd9c390e25338996e2d"`);
        await queryRunner.query(`DROP TABLE "members"`);
        await queryRunner.query(`DROP INDEX "IDX_d3f07b1964f2d0915e43fc8a4a"`);
        await queryRunner.query(`DROP INDEX "IDX_9641757bcd62af342e2aa5f7e1"`);
        await queryRunner.query(`DROP TABLE "households"`);
        await queryRunner.query(`DROP INDEX "IDX_763fd9caff55ea1f33aa146a4b"`);
        await queryRunner.query(`DROP TABLE "chapters"`);
        await queryRunner.query(`DROP INDEX "IDX_13c69424c440a0e765053feb4b"`);
        await queryRunner.query(`DROP INDEX "IDX_c69efb19bf127c97e6740ad530"`);
        await queryRunner.query(`DROP INDEX "IDX_cee5459245f652b75eb2759b4c"`);
        await queryRunner.query(`DROP INDEX "IDX_e36d23e1e7cf81ea77758bef79"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
    }

}
